ActiviKidWebUI/Components/FilterViewComponent.cs
using ActiviKidWebUI.Models.DataContext;
using ActiviKidWebUI.Models.ViewModel;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Mvc;

namespace ActiviKidWebUI.Components
{
    public class FilterViewComponent : ViewComponent
    {
        readonly ActiviKidDbContext db;
        public FilterViewComponent(ActiviKidDbContext db)
        {
            this.db = db;
        }


        public async Task<IViewComponentResult> InvokeAsync(int productId, string? lang)
        {
            ViewBag.Lang = lang;
            if (lang == null || lang == "az")
            {
                ViewBag.Category = new SelectList(db.Categories.ToList(), "Id", "Name");
                ViewBag.Color = new SelectList(db.Color.ToList(), "Id", "Name");
            }
           else {
                ViewBag.Category = new SelectList(db.CategoryRus.ToList(), "Id", "Name");
                ViewBag.Color = new SelectList(db.ColorRus.ToList(), "Id", "Name");
            }
            return View();

        }

    }
}

ActiviKidWebUI/Components/OurClientViewComponent.cs
using ActiviKidWebUI.Models.DataContext;
using ActiviKidWebUI.Models.ViewModel;
using Microsoft.AspNetCore.Mvc;

namespace ActiviKidWebUI.Components
{
    public class OurClientViewComponent : ViewComponent
    {
        readonly ActiviKidDbContext db;
        public OurClientViewComponent(ActiviKidDbContext db)
        {
            this.db = db;
        }


        public async Task<IViewComponentResult> InvokeAsync()
        {
            var client = db.OurClients.ToList();
            return View(client);

        }
    }
}

ActiviKidWebUI/Components/ProductViewComponent.cs
using ActiviKidWebUI.Models.DataContext;
using ActiviKidWebUI.Models.ViewModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace ActiviKidWebUI.Components
{
    public class ProductViewComponent : ViewComponent
    {
        readonly ActiviKidDbContext db;
        public ProductViewComponent(ActiviKidDbContext db)
        {
            this.db = db;
        }


        public async Task<IViewComponentResult> InvokeAsync(int category = 0, bool bestseller = false,
            bool newarrival = false, bool mostliked = false, bool top = false, bool randoms = false,
            int colorId = 0, int min = 0, int max = 0, string lang = "az")
        {
            var vm = new ProductViewModel();
            if (lang == null || lang == "az")
            {
                vm.Products = db.Products.Include(p => p.ProductColorSizeCount).Include(p => p.Category).Where(p => p.DeletedDate == null).ToList();
                vm.ProductColorSizeCounts = db.ProductColorSizeCount.ToList();
            }
            else
            {
                vm.Products = db.ProductRus.Include(p => p.ProductColorSizeCount).Include(p => p.Category).ToList();
                vm.ProductColorSizeCounts = db.ProductColorSizeCountRus.ToList();
            }
                
                if(category > 0)
            {
                vm.Products = vm.Products.Where(p => p.CategoryId == category).ToList();
            }
            if (top == true)
            {
                vm.Products = vm.Products.Where(p => p.Top == true).ToList();
            }
            if (bestseller)
            {
                ViewBag.bestseller = "best-seller";
                ViewBag.Class = "best-seller";
                vm.Products = vm.Products.Where(p => p.BestSeller == true).ToList();
            }
            if (newarrival)
            {
                ViewBag.newarrival = "new";
                ViewBag.Class = "new";
                vm.Products = vm.Products.Where(p => p.NewArrival == true).ToList();
            }
            if (mostliked)
            {
                ViewBag.mostliked = "most-liked";
                ViewBag.Class = "most-liked";
                vm.Products = vm.Products.Where(p => p.MostLiked == true).ToList();
            }
            if (colorId > 0)
            {
                vm.ProductColorSizeCounts = vm.ProductColorSizeCounts.Where(p=> p.ColorId == colorId).ToList();
            }
            if (min > 0)
            {
                vm.Products = vm.Products.Where(p => p.Price > min).ToList();
            }
            if (max > 0)
            {
                vm.Products = vm.Products.Where(p => p.Price < max).ToList();
            }
            if (randoms == true)
            {
                ViewBag.Random = "random";
                ViewBag.Class = "random";
            }

            if (vm.Products.Count() == 0 || vm.Products == null)
            {
                ViewBag.Notfound = "The product you are looking for is currently unavailable";
            }
            if (vm.ProductColorSizeCounts.Count() == 0 || vm.ProductColorSizeCounts == null)
            {
                ViewBag.Notfound = "The product you are looking for is currently unavailable";
            }
            return View(vm);

        }
    }
}

ActiviKidWebUI/Controllers/ShopController.cs
using ActiviKidWebUI.Models.DataContext;
using ActiviKidWebUI.Models.Entity;
using ActiviKidWebUI.Models.FormModel;
using ActiviKidWebUI.Models.ViewModel;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace ActiviKidWebUI.Controllers
{
    public class ShopController : Controller
    {
        readonly ActiviKidDbContext db;
        public ShopController(ActiviKidDbContext db)
        {
            this.db = db;
        }

        public IActionResult Index(FilterFormModel fm, string? lang, int id = 0)
        {
            if (id != 0)
            {
                ViewData["Id"] = id;
            }

            string cookieValueFromReqq = Request.Cookies["activiProduct"];

            var values = cookieValueFromReqq;
            string cookieValueFromReq = "";
            if (values == null)
            {
                var cookieOptions = new CookieOptions();
                cookieOptions.Expires = DateTime.Now.AddDays(2000);
                cookieOptions.Path = "/";
                var vauesss = Guid.NewGuid().ToString();
                Response.Cookies.Append("activiProduct", $"{vauesss}", cookieOptions);
            }
            else
            {
                cookieValueFromReq = Request.Cookies["activiProduct"];
            }


            var value = cookieValueFromReq;
            var count = 0;
            var order = new Orders();

            if (User.Identity.IsAuthenticated)
            {
                var user = User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.NameIdentifier).Value.ToString();
                count = count + db.Baskets.Where(p => p.UserId == user).ToList().Count();
                order = db.Orders.FirstOrDefault(p => p.UserId == user);
            }
            if (db.Orders.FirstOrDefault(p => p.UserId == value) != null)
            {
                order = db.Orders.FirstOrDefault(p => p.UserId == value);
            }

            count = count + db.Baskets.Where(p => p.UserId == value.ToString()).ToList().Count();

            var countt = 0;
            if (count > 0)
            {
                countt = count;
            }


            ViewBag.Count = countt;
            ViewBag.Order = null;
            if (order != null)
            {
                ViewBag.Order = order.UserId;
            }

       
            ViewBag.Lang = lang;

            ViewBag.Lang = lang;
            ViewData["ColorId"] = fm.ColorId;
            ViewData["CategoryId"] = fm.CategoryId;
            ViewData["Min"] = fm.Min;
            ViewData["Max"] = fm.Max;
            ViewData["BestSeller"] = fm.BestSeller;
            ViewData["MostLiked"] = fm.MostLiked;
            ViewData["Top"] = fm.Top;
            ViewData["NewArrival"] = fm.NewArrival;
            return View();
        }
    }
}

ActiviKidWebUI/Views/Shop/Index.cshtml
<!-- Page Header Start -->
<section class="page-header">
    <h2 class="page-title color--white">@LayoutResource.Shop</h2>
</section>
<!-- Page Header End -->
<!-- Breadcumb area Start -->
<div class="breadcumb-area section-padding">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <ul class="breadcumb">
                    <li class="breadcumb__list"><a class="breadcumb__link" href="index.html">@LayoutResource.Home</a></li>
                    <li class="breadcumb__list"><a class="breadcumb__link current" href="shop-list-view.html">@LayoutResource.Shop</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>
<!-- Breadcumb area End -->
<!-- Main content wrapper Start -->
<div class="main-content-wrapper">
    <div class="shop-area section-padding">
        <div class="container">
            <div class="row">
                @await Component.InvokeAsync("Filter", new{lang = ViewBag.Lang})
                <div class="col-lg-9 order-lg-2 order-1 mb-md--30">

                    <!-- Shop Layout Start -->
                    <div class="main-shop-wrapper">
                        <div class="tab-content" id="myTabContent-2">
                            <div class="tab-pane active" id="grid">
                                <div class="product-grid-view">
                                    <div class="row g-0">
                                        @await Component.InvokeAsync("Product", new{colorId = ViewData["ColorId"], 
                                        category = ViewData["CategoryId"], min = ViewData["Min"], max = ViewData["Max"], bestseller = ViewData["BestSeller"],
                                        mostliked = ViewData["MostLiked"], top = ViewData["Top"], newarrival = ViewData["NewArrival"], randoms = true, lang = ViewBag.Lang})
                                    </div>
                                </div>
                            </div>
                      
                        </div>
                      
                    </div>
                    <!-- Shop Layout End -->
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Main content wrapper End -->
<!-- Clients area Start -->
@await Component.InvokeAsync("OurClient")
<!-- Clients area End -->