ActiviKidWebUI/Components/CategoryViewComponent.cs
using ActiviKidWebUI.Models.DataContext;
using ActiviKidWebUI.Models.Entity;
using ActiviKidWebUI.Models.ViewModel;
using Microsoft.AspNetCore.Mvc;

namespace ActiviKidWebUI.Components
{
    public class CategoryViewComponent : ViewComponent
    {
        readonly ActiviKidDbContext db;
        public CategoryViewComponent(ActiviKidDbContext db)
        {
            this.db = db;
        }


        public async Task<IViewComponentResult> InvokeAsync(bool header = false, string? lang = "az")
        {
            var vm = new HomeViewModel();
            if (lang == null || lang == "az")
            {
                 vm.Category = db.Categories.ToList();
            }
            else
            {
                vm.Category = db.CategoryRus.ToList();
            }
            if (header == true)
            {
                ViewBag.header = header;
            }
            return View(vm);

        }
    }
}

ActiviKidWebUI/Components/DetailViewComponent.cs
using ActiviKidWebUI.Models.DataContext;
using ActiviKidWebUI.Models.ViewModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Drawing;
using System.Security.Claims;

namespace ActiviKidWebUI.Components
{
    public class DetailViewComponent : ViewComponent
    {
        readonly ActiviKidDbContext db;
        public DetailViewComponent(ActiviKidDbContext db)
        {
            this.db = db;
        }


        public async Task<IViewComponentResult> InvokeAsync(int productId, string? lang)
        {
            var vm = new ProductDetailViewModel();
            var colors = new List<dynamic>();

            if (lang == null || lang == "az")
            {
                

                vm.Product = db.Products.Include(p => p.ProductColorSizeCount).FirstOrDefault(p => p.Id == productId);

                vm.ProductColorSizeCount = db.ProductColorSizeCount.Where(p => p.ProductId == productId).ToList();
                foreach (var item in vm.ProductColorSizeCount.Where(p => p.ProductId == productId))
                {
                    foreach (var itemm in db.Color)
                    {
                        if (item.ColorId == itemm.Id)
                        {
                            colors.Add(itemm);
                        }

                    }

                }
                vm.Color = colors;
            }
            else{
                

                vm.Product = db.ProductRus.Include(p => p.ProductColorSizeCount).FirstOrDefault(p => p.Id == productId);

                vm.ProductColorSizeCount = db.ProductColorSizeCountRus.Where(p => p.ProductId == productId).ToList();
                foreach (var item in vm.ProductColorSizeCount.Where(p => p.ProductId == productId))
                {
                    foreach (var itemm in db.ColorRus)
                    {
                        if (item.ColorId == itemm.Id)
                        {
                            colors.Add(itemm);
                        }

                    }

                }
                vm.Color = colors;
            }

            return View(vm);

        }

    }
}

ActiviKidWebUI/Components/FilterViewComponent.cs
using ActiviKidWebUI.Models.DataContext;
using ActiviKidWebUI.Models.ViewModel;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Mvc;

namespace ActiviKidWebUI.Components
{
    public class FilterViewComponent : ViewComponent
    {
        readonly ActiviKidDbContext db;
        public FilterViewComponent(ActiviKidDbContext db)
        {
            this.db = db;
        }


        public async Task<IViewComponentResult> InvokeAsync(int productId, string? lang)
        {
            ViewBag.Lang = lang;
            if (lang == null || lang == "az")
            {
                ViewBag.Category = new SelectList(db.Categories.ToList(), "Id", "Name");
                ViewBag.Color = new SelectList(db.Color.ToList(), "Id", "Name");
            }
           else {
                ViewBag.Category = new SelectList(db.CategoryRus.ToList(), "Id", "Name");
                ViewBag.Color = new SelectList(db.ColorRus.ToList(), "Id", "Name");
            }
            return View();

        }

    }
}

ActiviKidWebUI/Components/FooterViewComponent.cs
using ActiviKidWebUI.Models.DataContext;
using ActiviKidWebUI.Models.ViewModel;
using Microsoft.AspNetCore.Mvc;

namespace ActiviKidWebUI.Components
{
    public class FooterViewComponent : ViewComponent
    {
        readonly ActiviKidDbContext db;
        public FooterViewComponent(ActiviKidDbContext db)
        {
            this.db = db;
        }


        public async Task<IViewComponentResult> InvokeAsync(string? lang)
        {
            var vm = new FooterViewModel();
            if (lang == null || lang == "az")
            {
                vm.SiteInfo = db.SiteInfos.FirstOrDefault();
                vm.Services = db.Services.ToList();
            }
           else {
                vm.SiteInfo = db.SiteInfos.FirstOrDefault();
                vm.Services = db.ServicesRus.ToList();
            }
            return View(vm);

        }
    }
}

ActiviKidWebUI/Components/HeaderViewComponent.cs
using ActiviKidWebUI.Models.DataContext;
using ActiviKidWebUI.Models.ViewModel;
using Microsoft.AspNetCore.Mvc;

namespace ActiviKidWebUI.Components
{
    public class HeaderViewComponent : ViewComponent
    {
        readonly ActiviKidDbContext db;
        public HeaderViewComponent(ActiviKidDbContext db)
        {
            this.db = db;
        }


        public async Task<IViewComponentResult> InvokeAsync(string lang, string? order)
        {
            var vm = new FooterViewModel();
            vm.SiteInfo = db.SiteInfos.FirstOrDefault();
            ViewBag.Order = order;
            ViewBag.Lang = lang;

            return View(vm);

        }
    }
}

ActiviKidWebUI/Components/OurClientViewComponent.cs
using ActiviKidWebUI.Models.DataContext;
using ActiviKidWebUI.Models.ViewModel;
using Microsoft.AspNetCore.Mvc;

namespace ActiviKidWebUI.Components
{
    public class OurClientViewComponent : ViewComponent
    {
        readonly ActiviKidDbContext db;
        public OurClientViewComponent(ActiviKidDbContext db)
        {
            this.db = db;
        }


        public async Task<IViewComponentResult> InvokeAsync()
        {
            var client = db.OurClients.ToList();
            return View(client);

        }
    }
}

ActiviKidWebUI/Components/ProductViewComponent.cs
using ActiviKidWebUI.Models.DataContext;
using ActiviKidWebUI.Models.ViewModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace ActiviKidWebUI.Components
{
    public class ProductViewComponent : ViewComponent
    {
        readonly ActiviKidDbContext db;
        public ProductViewComponent(ActiviKidDbContext db)
        {
            this.db = db;
        }


        public async Task<IViewComponentResult> InvokeAsync(int category = 0, bool bestseller = false,
            bool newarrival = false, bool mostliked = false, bool top = false, bool randoms = false,
            int colorId = 0, int min = 0, int max = 0, string lang = "az")
        {
            var vm = new ProductViewModel();
            if (lang == null || lang == "az")
            {
                vm.Products = db.Products.Include(p => p.ProductColorSizeCount).Include(p => p.Category).Where(p => p.DeletedDate == null).ToList();
                vm.ProductColorSizeCounts = db.ProductColorSizeCount.ToList();
            }
            else
            {
                vm.Products = db.ProductRus.Include(p => p.ProductColorSizeCount).Include(p => p.Category).ToList();
                vm.ProductColorSizeCounts = db.ProductColorSizeCountRus.ToList();
            }
                
                if(category > 0)
            {
                vm.Products = vm.Products.Where(p => p.CategoryId == category).ToList();
            }
            if (top == true)
            {
                vm.Products = vm.Products.Where(p => p.Top == true).ToList();
            }
            if (bestseller)
            {
                ViewBag.bestseller = "best-seller";
                ViewBag.Class = "best-seller";
                vm.Products = vm.Products.Where(p => p.BestSeller == true).ToList();
            }
            if (newarrival)
            {
                ViewBag.newarrival = "new";
                ViewBag.Class = "new";
                vm.Products = vm.Products.Where(p => p.NewArrival == true).ToList();
            }
            if (mostliked)
            {
                ViewBag.mostliked = "most-liked";
                ViewBag.Class = "most-liked";
                vm.Products = vm.Products.Where(p => p.MostLiked == true).ToList();
            }
            if (colorId > 0)
            {
                vm.ProductColorSizeCounts = vm.ProductColorSizeCounts.Where(p=> p.ColorId == colorId).ToList();
            }
            if (min > 0)
            {
                vm.Products = vm.Products.Where(p => p.Price > min).ToList();
            }
            if (max > 0)
            {
                vm.Products = vm.Products.Where(p => p.Price < max).ToList();
            }
            if (randoms == true)
            {
                ViewBag.Random = "random";
                ViewBag.Class = "random";
            }

            if (vm.Products.Count() == 0 || vm.Products == null)
            {
                ViewBag.Notfound = "The product you are looking for is currently unavailable";
            }
            if (vm.ProductColorSizeCounts.Count() == 0 || vm.ProductColorSizeCounts == null)
            {
                ViewBag.Notfound = "The product you are looking for is currently unavailable";
            }
            return View(vm);

        }
    }
}

ActiviKidWebUI/Controllers/AboutController.cs
using ActiviKidWebUI.Models.DataContext;
using ActiviKidWebUI.Models.Entity;
using ActiviKidWebUI.Models.ViewModel;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace ActiviKidWebUI.Controllers
{
    public class AboutController : Controller
    {
        readonly ActiviKidDbContext db;
        public AboutController(ActiviKidDbContext db)
        {
            this.db = db;
        }
        public IActionResult Index(string? lang)
        {

            string cookieValueFromReqq = Request.Cookies["activiProduct"];

            var values = cookieValueFromReqq;
            string cookieValueFromReq = "";
            if (values == null)
            {
                var cookieOptions = new CookieOptions();
                cookieOptions.Expires = DateTime.Now.AddDays(2000);
                cookieOptions.Path = "/";
                var vauesss = Guid.NewGuid().ToString();
                Response.Cookies.Append("activiProduct", $"{vauesss}", cookieOptions);
            }
            else
            {
                cookieValueFromReq = Request.Cookies["activiProduct"];
            }


            var value = cookieValueFromReq;
            var count = 0;
            var order = new Orders();

            if (User.Identity.IsAuthenticated)
            {
                var user = User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.NameIdentifier).Value.ToString();
                count = count + db.Baskets.Where(p => p.UserId == user).ToList().Count();
                order = db.Orders.FirstOrDefault(p => p.UserId == user);
            }
            if (db.Orders.FirstOrDefault(p => p.UserId == value) != null)
            {
                order = db.Orders.FirstOrDefault(p => p.UserId == value);
            }

            count = count + db.Baskets.Where(p => p.UserId == value.ToString()).ToList().Count();

            var countt = 0;
            if (count > 0)
            {
                countt = count;
            }


            ViewBag.Count = countt;
            ViewBag.Order = null;
            if (order != null)
            {
                ViewBag.Order = order.UserId;
            }

            
            ViewBag.Lang = lang;

            var vm = new AbourUsViewModel();
           
            if (lang == null || lang == "az")
            {
                vm.AboutUs = db.AboutUs.FirstOrDefault();
            }
            else
            {
                vm.AboutUs = db.AboutUsRus.FirstOrDefault();
            }
            return View(vm);

        }
    }
}

ActiviKidWebUI/Controllers/ContactController.cs
using ActiviKidWebUI.Models.Entity;
using Microsoft.AspNetCore.Mvc;
using System.Net.Mail;
using System.Net;
using ActiviKidWebUI.Models.DataContext;
using ActiviKidWebUI.Models.FormModel;
using System.Security.Claims;
using ActiviKidWebUI.Models.ViewModel;

namespace ActiviKidWebUI.Controllers
{
    public class ContactController : Controller
    {

        readonly ActiviKidDbContext db;
        public ContactController(ActiviKidDbContext db)
        {
            this.db = db;
        }
        public IActionResult Index(string? lang = null)
        {
          
            string cookieValueFromReqq = Request.Cookies["activiProduct"];

            var values = cookieValueFromReqq;
            string cookieValueFromReq = "";
            if (values == null)
            {
                var cookieOptions = new CookieOptions();
                cookieOptions.Expires = DateTime.Now.AddDays(2000);
                cookieOptions.Path = "/";
                var vauesss = Guid.NewGuid().ToString();
                Response.Cookies.Append("activiProduct", $"{vauesss}", cookieOptions);
            }
            else
            {
                cookieValueFromReq = Request.Cookies["activiProduct"];
            }


            var value = cookieValueFromReq;
            var count = 0;
            var order = new Orders();

            if (User.Identity.IsAuthenticated)
            {
                var user = User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.NameIdentifier).Value.ToString();
                count = count + db.Baskets.Where(p => p.UserId == user).ToList().Count();
                order = db.Orders.FirstOrDefault(p => p.UserId == user);
            }
            if (db.Orders.FirstOrDefault(p => p.UserId == value) != null)
            {
                order = db.Orders.FirstOrDefault(p => p.UserId == value);
            }

            count = count + db.Baskets.Where(p => p.UserId == value.ToString()).ToList().Count();

            var countt = 0;
            if (count > 0)
            {
                countt = count;
            }


            ViewBag.Count = countt;
            ViewBag.Order = null;
            if (order != null)
            {
                ViewBag.Order = order.UserId;
            }

           
            ViewBag.Lang = lang;


            var fm = new ContactFormModel();
            fm.SiteInfo = db.SiteInfos.FirstOrDefault();
            return View(fm);
        }

        [HttpPost]
        public IActionResult Index(ContactFormModel fm, Contact contact)
        {
            contact = fm.Contact;
            fm.SiteInfo = db.SiteInfos.FirstOrDefault();

            var builder = new ConfigurationBuilder()
                .SetBasePath(Directory.GetCurrentDirectory()).AddJsonFile("appsettings.json");
                var configuration = builder.Build();
                var host = configuration["Gmail:Host"];
                var port = int.Parse(configuration["Gmail:Port"]);
                var username = configuration["Gmail:Username"];
                var password = configuration["Gmail:Password"];
                var displayName = configuration["Gmail:DisplayName"];

                var enable = bool.Parse(configuration["Gmail:SMTP:starttls:enable"]);

                MailMessage mail = new MailMessage($"{contact.Email}", $"{username}");
                mail.Subject = displayName;


                mail.Body = $@"
               <html>
               <head> 
               <style>
               h6{"font-size: 2rem;"}
               p{""} 

              </style>
              </head>
              <body>
              <h6>Email: {contact.Email} </h6>
              <h6>Full Name: {contact.FullName}</h6> 
               <p>{contact.Message}</p>
            </body>
            </html>";
                mail.IsBodyHtml = true;




                SmtpClient smtpClient = new SmtpClient(host, port);
                smtpClient.Credentials = new NetworkCredential(username, password);
                smtpClient.EnableSsl = true;
                smtpClient.Send(mail);

                contact.Isanswerd = false;
            contact.Address = contact.Email;
            contact.Isanswerd = false;
            
                db.Add(contact);
                db.SaveChanges();
                ViewBag.msg = "Your message has been sent successfully";
                ModelState.Clear();
                return View(fm);


        }
    }
}

ActiviKidWebUI/Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ActiviKidWebUI.Models.DataContext;

namespace ActiviKidWebUI.Controllers
{
    public class OrderController : Controller
    {
        readonly ActiviKidDbContext db;

        public OrderController(ActiviKidDbContext db)
        {
            this.db = db;
        }
        public IActionResult Index(string id)
        {
            var order = db.Orders.Include(p=>p.Product).Where(p=>p.UserId == id).ToList();

            return View(order);
        }
    }
}

ActiviKidWebUI/Views/Shared/Components/Header/Default.cshtml
@model FooterViewModel
<header class="header header-1">
    <div class="header-top header-1--top">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-8 text-center text-lg-start">

                    <!-- Contact Info Start -->
                    <ul class="contact-info contact-info--1">
                        <li class="contact-info__list">@LayoutResource.Call_Us : <span>+@Model.SiteInfo.Number</span></li>
                        <li class="contact-info__list">email : <a href="mailto:@Model.SiteInfo.Email">@Model.SiteInfo.Email</a></li>
                           @if (!User.Identity.IsAuthenticated)
                            {
                        <li class="contact-info__list"><a asp-controller="account" asp-action="login">Sign In</a></li>
                            <li class="contact-info__list"><a asp-controller="account" asp-action="register">Sign Up</a></li>
                        }
                        else
                        {
                        <li class="contact-info__list"><a asp-controller="account" asp-action="logout">Sign Out</a></li>
                        <li class="contact-info__list"><a asp-controller="account" asp-action="register">Sign Up</a></li>
                        }
                    </ul>
                    <!-- Contact Info End -->

                </div>
                <div class="col-lg-4">

                    <!-- Header Top Nav Start -->
                    <div class="header-top__nav header-top__nav--1 d-flex justify-content-lg-end justify-content-center">
                 
                        <div class="language-selector header-top__nav--item">
                            <div class="dropdown header-top__dropdown">
                                <a class="dropdown-toggle" id="languageID" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <img src="~/assets/img/lan1.jpg" alt="English"> ENGLISH
                                    <i class="fa fa-angle-down"></i>
                                </a>
                                <div class="dropdown-menu" aria-labelledby="languageID">
                                    <a class="dropdown-item" id="eng" asp-controller="home" asp-action="index" asp-route-lang="az"><img src="~/assets/img/icons8-azerbaijan-48.png" alt="Azerbaijan"> Azerbaijan</a>
                                    <a class="dropdown-item" id="az" asp-controller="home" asp-action="index" asp-route-lang="en"><img src="~/assets/img/icons8-united-kingdom-48.png" alt="English">English</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- Header Top Nav End -->
                </div>
            </div>
        </div>
    </div>
    <div class="header-middle header-1--middle">
        <div class="container-fluid">
            <div class="row align-items-center">
                <div class="col-xl-2 col-lg-3 col-sm-4">
                    <div class="header-middle__left">
                        <!-- Logo Start -->
                        <a href="index.html" class="logo-box">
                            <img src="~/assets/img/@Model.SiteInfo.Logo" alt="logo" class="img-fluid">
                        </a>
                        <!-- Logo End -->
                        <!-- Category Nav Start -->
                        <div class="category-nav d-lg-block d-none">
                            <h2 class="category-nav__title" id="js-cat-nav-title"><i class="fa fa-bars"></i> <span>@LayoutResource.Categories</span></h2>

                            <ul class="category-nav__menu hidden-in-default" id="js-cat-nav">
                                <li class="category-nav__menu__item has-children">
                                    @await Component.InvokeAsync("Category", new{header = true, lang = ViewBag.Lang})
                                </li>

                            </ul>
                        </div>
                        <!-- Category Nav End -->

                    </div>
                </div>
                <div class="col-xl-8 col-lg-7 order-3 order-lg-2">

                </div>
                <div class="col-lg-2 col-sm-8 order-2 order-lg-3">

                    <!-- Header Cart Start -->
                    <div class="header-cart header-cart--1">
                        <a asp-controller="basket" asp-action="index" class="header-cart__dropdown-toggle" >
                            <i class="fa-solid fa-basket-shopping"></i>
                                <sup class="header-cart__count" id="basket-cart">@ViewBag.Count</sup>
                        </a>
               
                    </div>
                    <!-- Header Cart End -->

                </div>
                <div class="col-12 d-lg-none order-4">
                    <!-- Category Mobile Menu Start -->
                    <div class="category-moble-menu"></div>
                    <!-- Category Mobile Menu End -->
                </div>
            </div>
        </div>
    </div>
    <div class="header-bottom header-1--bottom fixed-header">
        <div class="container-fluid">
            <div class="row justify-content-center">
                <div class="col-12">
                    <nav class="main-navigation">
                        <!-- Mainmenu Start -->
                        <ul class="mainmenu">
                            <li class="mainmenu__item">
                                <a asp-controller="home" asp-action="index" class="mainmenu__link">@LayoutResource.Home</a>
                            </li>
                            <li class="mainmenu__item">
                                <a asp-controller="About" asp-action="index" class="mainmenu__link">@LayoutResource.About_Us</a>
                            </li>
                            <li class="mainmenu__item">
                                <a asp-controller="shop" asp-action="index" class="mainmenu__link">@LayoutResource.Shop</a>
                               
                            </li>
                            <li class="mainmenu__item ">
                                <a asp-controller="news" asp-action="index" class="mainmenu__link">@LayoutResource.Blog</a>
                            </li>
                            <li class="mainmenu__item"><a asp-controller="Contact" asp-action="index" class="mainmenu__link">@LayoutResource.Contact_Us</a></li>
                              @if (!string.IsNullOrWhiteSpace(ViewBag.Order))
                                {
                                <li class="mainmenu__item"><a asp-controller="Order" asp-action="index" asp-route-id="@ViewBag.Order" class="mainmenu__link">My Order</a></li>
                                }
                        </ul>
                        <!-- Mainmenu End -->
                    </nav>
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    <!-- Main Mobile Menu Start -->
                    <div class="mobile-menu"></div>
                    <!-- Main Mobile Menu End -->
                </div>
            </div>
        </div>
    </div>
</header>